version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jenkins_dashboard_db
    environment:
      POSTGRES_DB: jenkins_dashboard
      POSTGRES_USER: jenkins_user
      POSTGRES_PASSWORD: jenkins_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jenkins_user -d jenkins_dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jenkins_dashboard_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jenkins-dashboard.com
      PGADMIN_DEFAULT_PASSWORD: admin_password_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: jenkins_dashboard_network 